## Essential Pandas for Machine Learning
<hr>

### Agenda

1. **Introduction to Pandas** - What is Pandas and why use it?
2. **Understanding Series & DataFrames** - Core data structures
3. **Loading CSV & JSON** - Reading external data
4. **Connecting Databases** - SQLite integration
5. **Descriptive Statistics** - Summarizing datasets
6. **Accessing Subsets of Data** - Rows, columns, filters
7. **Handling Missing Data** - Dealing with NaN values
8. **Dropping Rows & Columns** - Removing unwanted data
9. **Handling Duplicates** - Finding and removing duplicates
10. **Function Application** - map, apply, groupby, rolling, str
11. **Merge, Join & Concatenate** - Combining DataFrames
12. **Pivot Tables** - Summarizing with pivot tables
13. **Normalizing JSON** - Flattening nested JSON

<hr>

In [1]:
import pandas as pd
import numpy as np
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 1.1.5
NumPy version: 1.19.5

### 1. Introduction to Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

- **Series**: One-dimensional labeled array capable of holding any data type
- **DataFrame**: Two-dimensional labeled data structure with columns of potentially different types
- **Data I/O**: Read/write CSV, Excel, SQL, JSON, HTML, Parquet and many more formats
- **Data Cleaning**: Handle missing data, duplicates, outliers with ease
- **Data Transformation**: Group, pivot, merge, join, reshape your data
- **Time Series**: Powerful date/time functionality for temporal data
- **Performance**: Built on NumPy, vectorized operations for blazing speed

Think of Pandas as **Excel on steroids** - but programmable, reproducible, and way more powerful!

<hr>

In [2]:
# A quick taste of what's coming
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 32, 37, 28],
    'Salary': [50000, 68000, 75000, 62000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   32   68000
2  Charlie   37   75000
3    Diana   28   62000

### 2. Understanding Series & DataFrames

These are the two core data structures in Pandas. Let's create them from scratch!

<hr>

In [3]:
# Creating a Pandas Series with a custom index
fruits = pd.Series([10, 25, 8, 30], index=['Apples', 'Oranges', 'Bananas', 'Mangoes'])
print(fruits)

Apples     10
Oranges    25
Bananas     8
Mangoes    30
dtype: int64

In [4]:
# DataFrame from a dictionary of Series
data = {
    'Sales': pd.Series([100, 200, 150], index=['Q1', 'Q2', 'Q3']),
    'Profit': pd.Series([30, 50, 40], index=['Q1', 'Q2', 'Q3'])
}
df = pd.DataFrame(data)
df

    Sales  Profit
Q1    100      30
Q2    200      50
Q3    150      40

In [5]:
# Create a DataFrame with random data
np.random.seed(42)
random_df = pd.DataFrame(np.random.randn(5, 4),
                        columns=['A', 'B', 'C', 'D'])
random_df

              A          B          C          D
   0   0.496714  -0.138264   0.647689   1.523030
   1  -0.234153  -0.234137   1.579213   0.767435
   2  -0.469474   0.542560  -0.463418  -0.465730
   3   0.241962  -1.913280  -1.724918  -0.562288
   4  -1.012831   0.314247  -0.908024  -1.412304

### 3. Loading CSV & JSON

Real-world data comes in many formats. Pandas makes it easy to load them!

<hr>

In [6]:
# Load CSV from a URL
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)
print("Shape:", cars.shape)
cars.head()

Shape: (398, 9)

    MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration  Year Origin                       Name
0  18.0          8         307.0       130.0  3504.0          12.0    70    USA  chevrolet chevelle malibu
1  15.0          8         350.0       165.0  3693.0          11.5    70    USA          buick skylark 320
2  18.0          8         318.0       150.0  3436.0          11.0    70    USA         plymouth satellite
3  16.0          8         304.0       150.0  3433.0          12.0    70    USA            amc rebel sst
4  17.0          8         302.0       140.0  3449.0          10.5    70    USA            ford torino

In [7]:
# Loading JSON data
# You can read JSON from a file, URL, or string
json_str = '[{"name":"Alice","age":30,"city":"NYC"},{"name":"Bob","age":25,"city":"LA"},{"name":"Charlie","age":35,"city":"Chicago"}]' 
df_json = pd.read_json(json_str)
df_json

      name  age     city
0    Alice   30      NYC
1      Bob   25       LA
2  Charlie   35  Chicago

In [8]:
# Exploring loaded data
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)
cars.info()
print("\n--- Top 2 rows ---")
cars.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MPG           398 non-null    float64
 1   Cylinders     398 non-null    int64
 2   Displacement  398 non-null    float64
 3   Horsepower    392 non-null    float64
 4   Weight        398 non-null    float64
 5   Acceleration  398 non-null    float64
 6   Year          398 non-null    int64
 7   Origin        398 non-null    object
 8   Name          398 non-null    object
dtypes: float64(5), int64(2), object(2)
memory usage: 28.1+ KB

--- Top 2 rows ---

    MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration  Year Origin                       Name
0  18.0          8         307.0       130.0  3504.0          12.0    70    USA  chevrolet chevelle malibu
1  15.0          8         350.0       165.0  3693.0          11.5    70    USA          buick skylark 320

### 4. Connecting Databases

Pandas can read directly from SQL databases. Let's use SQLite as an example!

<hr>

In [9]:
# Connecting to a SQLite database
import sqlite3

# Create an in-memory database
conn = sqlite3.connect(':memory:')
cur = conn.cursor()
cur.execute("CREATE TABLE employees (id INT, name TEXT, dept TEXT, salary INT)")
cur.execute("INSERT INTO employees VALUES (1, 'Alice', 'Engineering', 85000)")
cur.execute("INSERT INTO employees VALUES (2, 'Bob', 'Marketing', 72000)")
cur.execute("INSERT INTO employees VALUES (3, 'Charlie', 'Engineering', 95000)")
conn.commit()

# Read directly into a DataFrame
df_sql = pd.read_sql_query("SELECT * FROM employees", conn)
print(df_sql)
conn.close()

   id     name         dept  salary
0   1    Alice  Engineering   85000
1   2      Bob    Marketing   72000
2   3  Charlie  Engineering   95000

### 5. Descriptive Statistics

Get a quick summary of your dataset with just one line!

<hr>

In [10]:
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)
cars.info()
print("\n--- Statistical Summary ---")
cars.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MPG           398 non-null    float64
 1   Cylinders     398 non-null    int64
 2   Displacement  398 non-null    float64
 3   Horsepower    392 non-null    float64
 4   Weight        398 non-null    float64
 5   Acceleration  398 non-null    float64
 6   Year          398 non-null    int64
 7   Origin        398 non-null    object
 8   Name          398 non-null    object
dtypes: float64(5), int64(2), object(2)
memory usage: 28.1+ KB

--- Statistical Summary ---

              MPG  Cylinders  Displacement  Horsepower      Weight  Acceleration       Year
count  398.000000      398.0    398.000000  392.000000   398.000000    398.000000  398.000000
mean    23.514459        5.5    193.425879  104.469388  2970.424623     15.568090   76.010050
std      7.815984        1.8    104.269838   38.491160   846.841774      2.757689    3.697627
min      9.000000        3.0     68.000000   46.000000  1613.000000      8.000000   70.000000
25%     17.500000        4.0    104.250000   75.000000  2223.750000     13.825000   73.000000
50%     23.000000        4.0    148.500000   95.000000  2803.500000     15.500000   76.000000
75%     29.000000        8.0    262.000000  128.000000  3608.000000     17.175000   79.000000
max     46.600000        8.0    455.000000  230.000000  5140.000000     24.800000   82.000000

### 6. Accessing Subsets of Data - Rows, Columns, Filters

Let's slice and dice our data in every way possible!

<hr>

In [11]:
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)

# Select only numeric columns
numeric_cols = cars.select_dtypes(include=[np.number])
print("Numeric columns only (shape):", numeric_cols.shape)

# Rename a column
cars_renamed = cars.rename(columns={'MPG': 'MilesPerGallon', 'Weight': 'Wt'})
print("\nAfter renaming columns:")
cars_renamed[['MilesPerGallon', 'Wt']].head(3)

Numeric columns only (shape): (398, 6)

After renaming columns:

   MilesPerGallon     Wt
0            18.0  3504.0
1            15.0  3693.0
2            18.0  3436.0

In [12]:
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)

# loc - label-based indexing
print("loc[0:3, ['MPG', 'Name']]:")
cars.loc[0:3, ['MPG', 'Name']]

loc[0:3, ['MPG', 'Name']]:

   MPG                       Name
0  18.0  chevrolet chevelle malibu
1  15.0          buick skylark 320
2  18.0         plymouth satellite
3  16.0            amc rebel sst

In [13]:
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)

# iloc - integer position based indexing
print("iloc[0:3, 0:3] (first 3 rows, first 3 columns):")
cars.iloc[0:3, 0:3]

iloc[0:3, 0:3] (first 3 rows, first 3 columns):

    MPG  Cylinders  Displacement
0  18.0          8         307.0
1  15.0          8         350.0
2  18.0          8         318.0

In [14]:
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)

# Boolean filtering - the real power
# Get cars with MPG > 30
high_mpg = cars[cars['MPG'] > 30]
print(f"Cars with MPG > 30: {len(high_mpg)}")

# Multiple conditions
filtered = cars[(cars['MPG'] > 25) & (cars['Cylinders'] == 4)]
print(f"Cars with MPG > 25 AND 4 cylinders: {len(filtered)}")

filtered[['MPG', 'Cylinders', 'Name']].head()

Cars with MPG > 30: 93
Cars with MPG > 25 AND 4 cylinders: 84

    MPG  Cylinders                       Name
0  33.5          4          mazda rx2 coupe
1  32.0          4          datsun 510 (sw)
2  30.5          4          opel 1900 sedan
3  32.5          4           toyota corona
4  30.0          4             ford pinto

### 7. Handling Missing Data

Real-world data is never clean. Let's learn how to handle those pesky NaN values!

<hr>

In [15]:
# Let's create data with missing values
missing_df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [1, 2, 3, 4, 5],
    'D': [np.nan, np.nan, np.nan, np.nan, 5]
})
print("Data with missing values:")
print(missing_df)
print("\nisnull() - where are the NaNs?")
missing_df.isnull()

Data with missing values:
     A    B  C    D
0  1.0  NaN  1  NaN
1  2.0  2.0  2  NaN
2  NaN  3.0  3  NaN
3  4.0  NaN  4  NaN
4  5.0  5.0  5  5.0

isnull() - where are the NaNs?

       A      B      C      D
0  False   True  False   True
1  False  False  False   True
2   True  False  False   True
3  False   True  False   True
4  False  False  False  False

In [16]:
# Handling missing data
missing_df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [1, 2, 3, 4, 5],
    'D': [np.nan, np.nan, np.nan, np.nan, 5]
})

# notnull()
print("notnull():")
print(missing_df.notnull())

# dropna() - drop rows with any NaN
print("\ndropna() - drop rows with any NaN:")
print(missing_df.dropna())

# fillna() - fill NaN with a value
print("\nfillna(0):")
print(missing_df.fillna(0))

# Fill with column mean
print("\nfillna with column mean:")
print(missing_df.fillna(missing_df.mean()))

notnull():
       A      B     C      D
0   True  False  True  False
1   True   True  True  False
2  False   True  True  False
3   True  False  True  False
4   True   True  True   True

dropna() - drop rows with any NaN:
     A    B  C    D
4  5.0  5.0  5  5.0

fillna(0):
     A    B  C    D
0  1.0  0.0  1  0.0
1  2.0  2.0  2  0.0
2  0.0  3.0  3  0.0
3  4.0  0.0  4  0.0
4  5.0  5.0  5  5.0

fillna with column mean:
     A    B  C    D
0  1.0  3.0  1  5.0
1  2.0  2.0  2  5.0
2  3.0  3.0  3  5.0
3  4.0  3.0  4  5.0
4  5.0  5.0  5  5.0

### 8. Dropping Rows & Columns

Sometimes you just need to get rid of stuff!

<hr>

In [17]:
# Dropping rows and columns
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500],
    'D': [1000, 2000, 3000, 4000, 5000]
})
print("Original DataFrame:")
print(df)

# Drop columns (axis=1)
print("\nDrop column B:")
print(df.drop('B', axis=1))

# Drop rows (axis=0)
print("\nDrop row 2:")
print(df.drop(2, axis=0))

# Drop multiple columns
print("\nDrop columns A and D:")
print(df.drop(['A', 'D'], axis=1))

# inplace=True modifies the original
print("\nUsing inplace=True (no new object created):")

Original DataFrame:
   A   B    C     D
0  1  10  100  1000
1  2  20  200  2000
2  3  30  300  3000
3  4  40  400  4000
4  5  50  500  5000

Drop column B:
   A    C     D
0  1  100  1000
1  2  200  2000
2  3  300  3000
3  4  400  4000
4  5  500  5000

Drop row 2:
   A   B    C     D
0  1  10  100  1000
1  2  20  200  2000
3  4  40  400  4000
4  5  50  500  5000

Drop columns A and D:
   B    C
0  10  100
1  20  200
2  30  300
3  40  400
4  50  500

Using inplace=True (no new object created):

### 9. Handling Duplicates

Find and remove duplicate rows in your dataset.

<hr>

In [18]:
# Finding and removing duplicates
dup_df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Diana'],
    'age': [25, 30, 35, 25, 30, 28],
    'city': ['NYC', 'LA', 'Chicago', 'NYC', 'LA', 'Boston']
})
print("Original with duplicates:")
print(dup_df)

# duplicated() - marks duplicate rows
print("\nduplicated():")
print(dup_df.duplicated())

# drop_duplicates() - removes duplicate rows
print("\ndrop_duplicates():")
print(dup_df.drop_duplicates())

# Keep only the last occurrence
print("\ndrop_duplicates(keep='last'):")
print(dup_df.drop_duplicates(keep='last'))

# Check duplicates in specific columns only
print("\nduplicated() on name column only:")
print(dup_df.duplicated(subset=['name']))

Original with duplicates:
      name  age     city
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    Alice   25      NYC
4      Bob   30       LA
5    Diana   28   Boston

duplicated():
0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

drop_duplicates():
      name  age     city
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
5    Diana   28   Boston

drop_duplicates(keep='last'):
      name  age     city
2  Charlie   35  Chicago
3    Alice   25      NYC
4      Bob   30       LA
5    Diana   28   Boston

duplicated() on name column only:
0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

### 10. Function Application

Transform your data with map(), apply(), groupby(), rolling() and string methods!

<hr>

In [19]:
# map() - apply a function element-wise to a Series
df = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie'],
                   'score': [85, 92, 78]})

# map with a dictionary
grade_map = {85: 'B', 92: 'A', 78: 'C'}
df['grade'] = df['score'].map(grade_map)
print("Using map() with dictionary:")
print(df)

# apply() - apply a function along an axis
print("\nUsing apply() on columns (axis=0):")
print(df[['score']].apply(lambda x: x * 1.1))

# apply() with a custom function
def categorize(score):
    if score >= 90:
        return 'Excellent'
    elif score >= 80:
        return 'Good'
    else:
        return 'Needs Improvement'

df['category'] = df['score'].apply(categorize)
print("\nUsing apply() with custom function:")
print(df)

Using map() with dictionary:
      name  score grade
0    Alice     85     B
1      Bob     92     A
2  Charlie     78     C

Using apply() on columns (axis=0):
   score
0   93.5
1  101.2
2   85.8

Using apply() with custom function:
      name  score grade          category
0    Alice     85     B              Good
1      Bob     92     A          Excellent
2  Charlie     78     C  Needs Improvement

In [20]:
# groupby() - split-apply-combine
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)

# Group by 'Origin' and calculate mean MPG
print("Average MPG by Origin:")
print(cars.groupby('Origin')['MPG'].mean())

# Group by multiple columns
print("\nAverage MPG by Origin and Cylinders:")
print(cars.groupby(['Origin', 'Cylinders'])['MPG'].mean())

# rolling() - rolling window calculations
print("\nRolling mean (window=3) of first 10 MPG values:")
print(cars['MPG'].head(10).rolling(window=3).mean())

Average MPG by Origin:
Origin
Europe    27.768116
Japan     30.450000
USA       20.083534
Name: MPG, dtype: float64

Average MPG by Origin and Cylinders:
Origin  Cylinders
Europe  4            30.487013
        6            24.011111
Japan   4            31.007692
        6            27.000000
USA     3            21.500000
        4            25.723881
        6            20.189091
        8            16.180769
Name: MPG, dtype: float64

Rolling mean (window=3) of first 10 MPG values:
0          NaN
1          NaN
2    17.000000
3    16.333333
4    17.000000
5    18.333333
6    19.666667
7    20.333333
8    20.000000
9    20.666667
Name: MPG, dtype: float64

In [21]:
# String methods - vectorized string operations
data = pd.DataFrame({'text': ['hello world', 'PYTHON is FUN', '   pandas   ', 'DATA SCIENCE']})

# str.lower()
data['lower'] = data['text'].str.lower()
# str.upper()
data['upper'] = data['text'].str.upper()
# str.strip() - remove whitespace
data['stripped'] = data['text'].str.strip()
# str.contains() - check if string contains a pattern
data['has_pandas'] = data['text'].str.contains('pandas', case=False)
# str.replace()
data['replaced'] = data['text'].str.replace(' ', '_')
# str.split()
data['split'] = data['text'].str.split()

print("String operations:")
data

String operations:

            text            lower           upper        stripped has_pandas        replaced               split
0     hello world      hello world      HELLO WORLD   hello world      False     hello_world      [hello, world]
1  PYTHON is FUN    python is fun    PYTHON IS FUN  PYTHON is FUN      False   PYTHON_is_FUN    [PYTHON, is, FUN]
2      pandas           pandas            PANDAS         pandas       True        ___pandas___           [pandas]
3    DATA SCIENCE    data science    DATA SCIENCE  DATA SCIENCE      False   DATA_SCIENCE    [DATA, SCIENCE]

### 11. Merge, Join & Concatenate

Combine multiple DataFrames like a pro!

<hr>

In [22]:
# Merge, Join & Concatenate
# merge() - like SQL JOIN
df1 = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'id': [1, 2, 4], 'score': [85, 92, 78]})

# Inner merge (only matching ids)
print("Inner merge:")
print(pd.merge(df1, df2, on='id', how='inner'))

# Left merge (keep all from df1)
print("\nLeft merge:")
print(pd.merge(df1, df2, on='id', how='left'))

# concat() - stack DataFrames vertically or horizontally
df_a = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df_b = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

print("\nVertical concatenation (concat along axis=0):")
print(pd.concat([df_a, df_b], axis=0))

print("\nHorizontal concatenation (concat along axis=1):")
print(pd.concat([df_a, df_b], axis=1))

# join() - join on index
df_x = pd.DataFrame({'salary': [50000, 60000]}, index=['Alice', 'Bob'])
df_y = pd.DataFrame({'age': [25, 30]}, index=['Alice', 'Bob'])
print("\nJoin on index:")
print(df_x.join(df_y))

Inner merge:
   id   name  score
0   1  Alice     85
1   2    Bob     92

Left merge:
   id     name  score
0   1    Alice   85.0
1   2      Bob   92.0
2   3  Charlie    NaN

Vertical concatenation (concat along axis=0):
   A  B
0  1  3
1  2  4
0  5  7
1  6  8

Horizontal concatenation (concat along axis=1):
   A  B  A  B
0  1  3  5  7
1  2  4  6  8

Join on index:
        salary  age
Alice   50000   25
Bob     60000   30

### 12. Pivot Tables

Summarize your data with pivot tables - the Excel feature, now in Python!

<hr>

In [23]:
# pivot_table() - create a spreadsheet-style pivot table
url = "https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/cars.csv"
cars = pd.read_csv(url)

# Create a pivot table: average MPG by Origin and Cylinders
pivot = pd.pivot_table(cars,
                       values='MPG',
                       index='Origin',
                       columns='Cylinders',
                       aggfunc='mean')
print("Pivot Table - Average MPG by Origin and Cylinders:")
pivot

Pivot Table - Average MPG by Origin and Cylinders:

Cylinders          3          4          5          6          8
Origin
Europe     22.000000  30.529412  27.366667  24.011111        NaN
Japan            NaN  31.007692        NaN  27.000000        NaN
USA        21.500000  25.723881        NaN  20.189091  16.180769

### 13. Normalizing JSON

Flatten nested JSON into a flat table!

<hr>

In [24]:
# json_normalize() - flatten nested JSON
from pandas import json_normalize

# Nested JSON data (list of dicts with nested dicts)
data = [
    {
        'name': 'Alice',
        'age': 30,
        'address': {'city': 'New York', 'state': 'NY', 'zip': 10001},
        'hobbies': ['reading', 'cycling']
    },
    {
        'name': 'Bob',
        'age': 25,
        'address': {'city': 'Los Angeles', 'state': 'CA', 'zip': 90001},
        'hobbies': ['gaming', 'hiking']
    },
    {
        'name': 'Charlie',
        'age': 35,
        'address': {'city': 'Chicago', 'state': 'IL', 'zip': 60601},
        'hobbies': ['cooking', 'photography']
    }
]

# Flatten the nested JSON
flat = json_normalize(data, sep='_')
print("Normalized JSON (nested address flattened):")
flat

Normalized JSON (nested address flattened):

      name  age address_city address_state  address_zip            hobbies
0    Alice   30     New York            NY        10001  [reading, cycling]
1      Bob   25  Los Angeles            CA        90001    [gaming, hiking]
2  Charlie   35      Chicago            IL        60601  [cooking, photography]